[package]
name = "observer_ward"
version = "0.1.0"
authors = ["Kali-Team <root@kali-team.cn>"]
edition = "2018"
description = "Identifies technologies used on a web page."
license = "MIT OR Apache-2.0"
[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
serde_derive = "1.0"
reqwest = { version = "0.10", features = ["socks", "blocking"] }
tokio = { version = "1.16", features = ["full"] }
futures = { version = "0.3", features = ["compat"] }
url = { version = "2.1.1", features = ["serde"] }
scraper = "0.10.1"
hex-literal = "0.3.3"
lazy_static = "1.4.0"
clap = "2.33.3"
colored = "2"
actix-web = "3"
actix-service = "1.0.0"
prettytable-rs = "^0.8"
textwrap = "0.14"
async-std = "1.7.0"
log = "0.4.0"
env_logger = "0.8.4"
encoding_rs = "0.8.28"
regex = { version = "1.3.1", default-features = false, features = ["std"] }
mime = "0.3.16"

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1"